openapi: 3.0.3
info:
  title: PhotoSoft Backend API - OpenAPI 3.0
  description: PhotoSoft Backend API Documentation
  contact:
    email: tharunvind@gmail.com
  version: 1.0.1
servers:
  - url: http://13.232.62.104/
tags:
  - name: Student
    description: Everything about Student
  - name: Teacher
    description: Everything about Teacher
  - name: School
    description: Everything about School

paths:
  /signup:
    post:
      tags:
        - School
      summary: Creates a new school
      description: This API  creates a new school. This API is consumed by the school component.
      requestBody:
        description: creates a new school
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - name
                - village
                - address
                - mandal
                - district
                - password
              properties:
                id:
                  type: string
                  example: 2020bcs0066
                name:
                  type: string
                  example: Tharun Vemula
                address:
                  type: string
                  example: '6301930763'
                village:
                  type: string
                  example: '2023-02-11T18:30:00.000Z'
                mandal:
                  type: string
                  example: '2023-02-11T18:30:00.000Z'
                district:
                  type: boolean
                  example: false
                password:
                  type: boolean
                  example: false
                phoneNumber:
                  type: string
                  example: Pala
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                id:
                  type: string
                  example: 2020bcs0066
                name:
                  type: string
                  example: Tharun Vemula
                address:
                  type: string
                  example: '6301930763'
                village:
                  type: string
                  example: '2023-02-11T18:30:00.000Z'
                mandal:
                  type: string
                  example: '2023-02-11T18:30:00.000Z'
                district:
                  type: boolean
                  example: false
                password:
                  type: boolean
                  example: false
                phoneNumber:
                  type: string
                  example: Pala

  /createStudent:
    post:
      tags:
        - Student
      summary: Creates a student record
      description: It Creates a student record

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: <ObjectID>
                name:
                  type: number
                  example: 0
                fatherName:
                  type: string
                  example: Security 1
                class:
                  type: string
                  example: Security 1
                section:
                  type: string
                  example: Security 1
                school:
                  type: string
                  example: Security 1
                address:
                  type: string
                  example: Security 1
                aadhaar:
                  type: string
                  example: Security 1
                photoUrl:
                  type: string
                  example: Security 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                id:
                  type: string
                  example: ObjectId
                name:
                  type: number
                  example: 0
                fatherName:
                  type: string
                  example: Security 1
                class:
                  type: string
                  example: Security 1
                section:
                  type: string
                  example: Security 1
                school:
                  type: string
                  example: Security 1
                address:
                  type: string
                  example: Security 1
                aadhaar:
                  type: string
                  example: Security 1
                photoUrl:
                  type: string
                  example: Security 1
        '400':
          description: Invalid status value

  /createTeacher:
    post:
      tags:
        - Teacher
      summary: Creates a student record
      description: It Creates a student record

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: <ObjectID>
                name:
                  type: number
                  example: 0
                employeeId:
                  type: string
                  example: Security 1
                designation:
                  type: string
                  example: Security 1
                phoneNumber:
                  type: string
                  example: Security 1
                school:
                  type: string
                  example: Security 1
                address:
                  type: string
                  example: Security 1
                aadhaar:
                  type: string
                  example: Security 1
                photoUrl:
                  type: string
                  example: Security 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                id:
                  type: string
                  example: ObjectId
                name:
                  type: number
                  example: 0
                employeeId:
                  type: string
                  example: Security 1
                designation:
                  type: string
                  example: Security 1
                phoneNumber:
                  type: string
                  example: Security 1
                school:
                  type: string
                  example: Security 1
                address:
                  type: string
                  example: Security 1
                aadhaar:
                  type: string
                  example: Security 1
                photoUrl:
                  type: string
                  example: Security 1
        '400':
          description: Invalid status value
      
  /login:
    post:
      tags:
        - School
      summary: Authenticates a School
      description: Returns a payload containing school data
      requestBody:
        description: Returns a payload containing school data
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: 2020bcs0066
                password:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/School'
 
components:
  schemas:
    Student:
      type: object
      required:
        - id
        - name
        - class
        - section
        - fatherName
        - school
        - address
        - aadhaar
      properties:
        id:
          type: string
          example: 2020bcs0066
        name:
          type: string
          example: Tharun Vemula
        class:
          type: string
          example: X
        section:
          type: string
          example: A
        fatherName:
          type: string
          example: dad
        school:
          type: string
          example: 6301930763
        address:
          type: string
          example: hyderabad
        aadhaar:
          type: string
          example: 914956003355

    Teacher:
      type: object
      required:
        - id
        - name
        - employeeId
        - designation
        - phoneNumber
        - school
        - address
        - aadhaar
      properties:
        id:
          type: string
          example: 2020bcs0066
        name:
          type: string
          example: Tharun Vemula
        employeeId:
          type: string
          example: X
        designation:
          type: string
          example: A
        phoneNumber:
          type: string
          example: dad
        school:
          type: string
          example: 6301930763
        address:
          type: string
          example: hyderabad
        aadhaar:
          type: string
          example: 914956003355
    School:
      type: object
      required:
        - id
        - name
        - village
        - phoneNumber
        - mandal
        - district
        - state
        - password
        - address
      properties:
        id:
          type: string
          example: 2020bcs0066
        name:
          type: string
          example: Tharun Vemula
        address:
          type: string
          example: X
        village:
          type: string
          example: A
        mandal:
          type: string
          example: dad
        district:
          type: string
          example: 6301930763
        state:
          type: string
          example: hyderabad
        password:
          type: string
          example: 914956003355
    
